// Package state manages the per-project (or global) state.json file that
// tracks uta's named "threads" — long-running contexts the user switches
// between like terminal tabs. A thread remembers its mode, the last
// session that ran inside it, and pointers into the shared context dir.
//
// The file lives in:
//
//   - <ProjectRoot>/.uta/state.json when uta is running inside a project
//   - <GlobalHome>/state.json otherwise (e.g. ~/.uta/state.json)
//
// Writes always go through paths.WriteFileAtomic so a crash mid-write
// can never leave a half-written file on disk.
//
// Concurrency: two uta processes writing state.json simultaneously is
// safe in the "no corruption" sense — atomic rename guarantees the
// final file is always a complete, parseable Index. But there is no
// cross-process lock, so concurrent writers are last-writer-wins: the
// loser's update is silently dropped. uta is a single-operator CLI;
// this matches expectations. If a future feature needs read-modify-
// write atomicity across processes, this is the boundary to revisit.
package state

import (
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/google/uuid"

	"github.com/unleashtheagents/uta/internal/paths"
)

// Filename is the on-disk name of the thread-index document inside any
// state directory.
const Filename = "state.json"

// currentVersion is the schema version stamped into freshly written
// state files. Bumped whenever Index gains an incompatible field.
const currentVersion = 1

// Thread is one named context. A user juggling dev work and ops work
// keeps one Thread per workstream — switching between them swaps the
// "current session" that uta resume / uta run hang their state off.
type Thread struct {
	// ID is a stable opaque identifier, immune to renames. Generated by
	// New(); never rewritten.
	ID string `json:"id"`
	// Name is the short human handle (dev-feature-x, ops-monthly-recap).
	// Unique within a single Index.
	Name string `json:"name"`
	// Mode is the MissionProfile this thread was created under (dev,
	// audit, comms, …). Informational — uta does not auto-apply it on
	// switch; the user still passes --mode where relevant.
	Mode string `json:"mode,omitempty"`
	// ActiveSessionID is the session id of the most recent run/resume/
	// improve invocation made while this thread was active. `uta resume`
	// with no args reads this.
	ActiveSessionID string `json:"active_session_id,omitempty"`
	// ContextRefs is a free-form list of paths/handles into the shared
	// context dir that belong to this thread. Reserved for iter 11's
	// cross-thread memory sharing; current iter only stores them.
	ContextRefs []string  `json:"context_refs,omitempty"`
	CreatedAt   time.Time `json:"created_at"`
	LastUsedAt  time.Time `json:"last_used_at"`
}

// Index is the on-disk envelope: a schema version, the id of the
// currently-active thread, and the list of known threads.
type Index struct {
	Version      int       `json:"version"`
	ActiveThread string    `json:"active_thread,omitempty"`
	Threads      []*Thread `json:"threads,omitempty"`
}

// Path returns the absolute path to state.json inside stateDir. Does
// not verify existence.
func Path(stateDir string) string {
	return filepath.Join(stateDir, Filename)
}

// Load reads state.json from stateDir. A missing file is not an error
// — the caller gets an empty Index it can mutate and Save. Malformed
// JSON is reported as an error rather than silently dropped so a
// corrupted file is not overwritten without the operator noticing.
func Load(stateDir string) (*Index, error) {
	if stateDir == "" {
		return nil, errors.New("state: stateDir is required")
	}
	data, err := os.ReadFile(Path(stateDir))
	if err != nil {
		if os.IsNotExist(err) {
			return &Index{Version: currentVersion}, nil
		}
		return nil, err
	}
	var idx Index
	if err := json.Unmarshal(data, &idx); err != nil {
		return nil, fmt.Errorf("state: parse %s: %w", Filename, err)
	}
	if idx.Version == 0 {
		idx.Version = currentVersion
	}
	return &idx, nil
}

// Save serializes idx and atomically replaces state.json in stateDir.
// stateDir is created if missing.
func Save(stateDir string, idx *Index) error {
	if stateDir == "" {
		return errors.New("state: stateDir is required")
	}
	if idx == nil {
		return errors.New("state: index is nil")
	}
	if idx.Version == 0 {
		idx.Version = currentVersion
	}
	if err := os.MkdirAll(stateDir, 0o755); err != nil {
		return err
	}
	buf, err := json.MarshalIndent(idx, "", "  ")
	if err != nil {
		return fmt.Errorf("state: marshal: %w", err)
	}
	buf = append(buf, '\n')
	return paths.WriteFileAtomic(Path(stateDir), buf, 0o644)
}

// Find returns the thread whose ID or Name matches needle, or nil if
// no match. Matches are exact; there is no prefix / fuzzy mode.
func (i *Index) Find(needle string) *Thread {
	needle = strings.TrimSpace(needle)
	if needle == "" || i == nil {
		return nil
	}
	for _, t := range i.Threads {
		if t == nil {
			continue
		}
		if t.ID == needle || t.Name == needle {
			return t
		}
	}
	return nil
}

// Active returns the currently-active thread, or nil if none is set.
func (i *Index) Active() *Thread {
	if i == nil || i.ActiveThread == "" {
		return nil
	}
	return i.Find(i.ActiveThread)
}

// New creates and inserts a fresh thread. Errors if a thread with the
// same name already exists — names are the operator's handle, so a
// duplicate would be ambiguous in CLI output. The new thread is
// returned but NOT made active; call SetActive afterwards if you want
// that.
func (i *Index) New(name, mode string) (*Thread, error) {
	name = strings.TrimSpace(name)
	if name == "" {
		return nil, errors.New("state: thread name is required")
	}
	if i.Find(name) != nil {
		return nil, fmt.Errorf("state: thread %q already exists", name)
	}
	now := time.Now().UTC()
	t := &Thread{
		ID:         uuid.NewString(),
		Name:       name,
		Mode:       strings.TrimSpace(mode),
		CreatedAt:  now,
		LastUsedAt: now,
	}
	i.Threads = append(i.Threads, t)
	return t, nil
}

// SetActive marks the thread matching needle (id or name) as the
// active one. Errors if no such thread exists. Touches LastUsedAt on
// the newly-activated thread so it sorts to the top of `thread list`.
func (i *Index) SetActive(needle string) (*Thread, error) {
	t := i.Find(needle)
	if t == nil {
		return nil, fmt.Errorf("state: no thread matching %q", needle)
	}
	i.ActiveThread = t.ID
	t.LastUsedAt = time.Now().UTC()
	return t, nil
}

// TouchActiveSession is the single hook the engine uses to record
// "the session that just ran belongs to the active thread." It loads
// state.json from stateDir, finds the active thread, writes
// sessionID into it, stamps LastUsedAt, and saves. A no-op (no
// error) when there is no active thread — callers should not have to
// care whether the user has bothered to set one up.
//
// stateDir is the App.StateDir of the invocation: project's .uta when
// in a project, global home otherwise.
func TouchActiveSession(stateDir, sessionID string) error {
	if stateDir == "" || sessionID == "" {
		return nil
	}
	idx, err := Load(stateDir)
	if err != nil {
		return err
	}
	t := idx.Active()
	if t == nil {
		return nil
	}
	t.ActiveSessionID = sessionID
	t.LastUsedAt = time.Now().UTC()
	return Save(stateDir, idx)
}
